services:
  db:
    image: mysql:5.7
    container_name: dashboard-db
    restart: unless-stopped
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      SERVICE_NAME: mysql
    networks:
      - dashboard-app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3005:3000
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - dashboard-app

networks:
  dashboard-app:
    driver: bridge
