{
 "title": "GS_Dashboard",
 "time": { "from": "2020-05-21T04:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "from",
    "query": "2020-05-21,2020-05-28, 2021-05-28"
   },
   { "name": "to" }
  ]
 },
 "panels": [
  {
   "title": "users_with_biggest_number_of_hosted_growth_sessions",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT gs_count.host_name, total_gs hosted_growth_sessions, count total_number_of_attendees\nFROM (\n\tSELECT u.name host_name, COUNT(growth_session_id) total_gs\n\tFROM growth_session_user gsu\n\tJOIN users u ON u.id = gsu.user_id\n\tJOIN growth_sessions gs ON gs.id = gsu.growth_session_id\n\tWHERE gsu.user_type_id = 1 AND gs.date BETWEEN '$from' AND '$to'\n\tGROUP BY gsu.user_id\n) gs_count\nJOIN\n(\n\tSELECT COUNT(user_id) count, u.name host_name\n\tFROM (\n\tSELECT user_id, gsu.growth_session_id, gs_owners.owner_id\n\t\tFROM growth_session_user gsu\n\t\tJOIN (\n  \t\t\tSELECT gsu.growth_session_id gs_id, user_id owner_id\n  \t\t\tFROM growth_session_user gsu\n  \t\t\tWHERE gsu.user_type_id = 1\n\t\t\t) gs_owners \n\t\t\tON gs_owners.gs_id = gsu.growth_session_id\n\t\tJOIN growth_sessions gs ON gs.id = gsu.growth_session_id\n\t\tWHERE gs.date BETWEEN '$from' AND '$to'\n\t) data\n\tJOIN users u ON u.id = data.owner_id\n\tGROUP BY owner_id\n) user_count ON gs_count.host_name = user_count.host_name\nORDER BY total_gs DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "times_users_participated_in_one_gs_together",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT u1.name as user_1,\n\tCOUNT(CONCAT(gsu1.user_id, '_', gsu2.user_id)) times_mobbed_together,\n\tu2.name as user_2\nFROM growth_session_user gsu1\nJOIN growth_session_user gsu2\n\tON gsu1.growth_session_id = gsu2.growth_session_id AND \n\tgsu1.user_id <> gsu2.user_id\nJOIN users u1 ON gsu1.user_id = u1.id\nJOIN users u2 ON gsu2.user_id = u2.id\nJOIN growth_sessions gs ON gs.id = gsu1.growth_session_id\nWHERE u1.is_vehikl_member = 1 AND \n\tu2.is_vehikl_member = 1 AND\n  gsu1.user_id > gsu2.user_id AND\n  gs.date BETWEEN '$from' AND '$to'\nGROUP BY gsu1.user_id, gsu2.user_id\nORDER BY times_mobbed_together DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "total_gs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) count\nFROM growth_sessions\nWHERE date BETWEEN '$from' AND '$to';\n\n\n"
    }
   ]
  },
  {
   "title": "max_gs_attendees",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(attendee_count.count)\nFROM\n(\n  SELECT count(user_id) count\n  FROM growth_session_user gsu\n  JOIN growth_sessions gs ON gs.id = gsu.growth_session_id\n  WHERE gs.date BETWEEN '$from' AND '$to'\n  GROUP BY growth_session_id\n) attendee_count;\n"
    }
   ]
  },
  {
   "title": "avg_attendees_per_gs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(attendee_count.count)\nFROM\n(\n  SELECT COUNT(user_id) count\n  FROM growth_session_user gsu\n  JOIN growth_sessions gs ON gs.id = gsu.growth_session_id\n  WHERE gsu.user_type_id = 2 AND \n        gs.date BETWEEN '$from' AND '$to'\n  GROUP BY growth_session_id\n) attendee_count;"
    }
   ]
  },
  {
   "title": "total_hrs_spent_on_gs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(length)\nFROM (\n\tSELECT (TIME_TO_SEC(end_time) - TIME_TO_SEC(start_time))/60/60 length\n\tFROM growth_sessions gs\n  WHERE gs.date BETWEEN '$from' AND '$to'\n) gs_length;\n"
    }
   ]
  },
  {
   "title": "max_number_of_gs_hosted_in_a_day",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(growth_sessions_count.count)\nFROM\n(\n  SELECT COUNT(id) count\n  FROM growth_sessions gs\n  WHERE gs.date BETWEEN '$from' AND '$to'\n  GROUP BY gs.date\n) growth_sessions_count;\n\n\n"
    }
   ]
  },
  {
   "title": "avg_number_of_daily_gs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(growth_sessions_count.count)\nFROM\n(\n  SELECT COUNT(id) count\n  FROM growth_sessions gs\n  WHERE gs.date BETWEEN '$from' AND '$to'\n  GROUP BY gs.date\n) growth_sessions_count;\n\n\n"
    }
   ]
  },
  {
   "title": "total_unique_participants",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT github_nickname)\nFROM users u\nJOIN growth_session_user gsu ON u.id = gsu.user_id\nJOIN growth_sessions gs ON gs.id = gsu.growth_session_id\nWHERE gs.date BETWEEN '$from' AND '$to';\n"
    }
   ]
  },
  {
   "title": "max_public_guests_in_a_gs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(gsu.growth_session_id) guest_attendee_count \nFROM growth_session_user gsu\nJOIN users u ON gsu.user_id = u.id\nJOIN growth_sessions gs ON gsu.growth_session_id = gs.id\nWHERE gsu.user_type_id = 2 AND \n      gs.is_public = 1 AND \n      gs.date BETWEEN '$from' AND '$to' AND \n      u.is_vehikl_member = 0\nGROUP BY gsu.growth_session_id\nORDER BY guest_attendee_count DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "avg_gs_duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(length)\nFROM (\n\tSELECT (TIME_TO_SEC(end_time) - TIME_TO_SEC(start_time))/60 length\n\tFROM growth_sessions gs\n  WHERE gs.date BETWEEN '$from' AND '$to'\n) gs_length;\n"
    }
   ]
  },
  {
   "title": "total_unique_guests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT github_nickname)\nFROM users u\nJOIN growth_session_user gsu ON gsu.user_id = u.id\nJOIN growth_sessions gs ON gs.id = gsu.growth_session_id\nWHERE gs.date BETWEEN '$from' AND '$to' AND\n      u.is_vehikl_member = 0;"
    }
   ]
  },
  {
   "title": "private_vs_public_growth_sessions",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(is_public) public\nFROM growth_sessions gs\nWHERE gs.date BETWEEN '$from' AND '$to' AND \n      is_public = 1;"
    },
    {
     "rawSql": "SELECT COUNT(is_public) private\nFROM growth_sessions gs\nWHERE gs.date BETWEEN '$from' AND '$to' AND is_public = 0;"
    }
   ]
  },
  {
   "title": "gs_number_and_attendance_over_time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT time, COUNT(growth_session_id) total_gs, SUM(user_count) total_attendees\nFROM (\n\tSELECT growth_session_id, COUNT(user_id) user_count, CONVERT_TZ(CAST(date as datetime),'-4:00','+0:00') time\n\tFROM growth_session_user gsu\n\tJOIN growth_sessions gs ON gs.id = gsu.growth_session_id\n  WHERE gs.date BETWEEN '$from' AND '$to'\n\tGROUP BY growth_session_id\n) data\nGROUP BY time;"
    }
   ]
  },
  {
   "title": "top_users_with_most_attended_gs",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT u.name, COUNT(growth_session_id) total_gs \nFROM growth_session_user gsu\nJOIN users u ON u.id = gsu.user_id\nJOIN growth_sessions gs ON gs.id = gsu.growth_session_id\nWHERE gsu.user_type_id = 2 AND \n      gs.date BETWEEN '$from' AND '$to'\nGROUP BY gsu.user_id\nORDER BY total_gs DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "gs_with_vs_without_limit",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(count) gs_with_limit\nFROM (\n\tSELECT COUNT(id) count\n\tFROM growth_sessions gs\n\tWHERE attendee_limit < 1000 AND \n\t      gs.date BETWEEN '$from' AND '$to'\n\tGROUP BY attendee_limit\n) data;"
    },
    {
     "rawSql": "SELECT SUM(count) gs_with_no_limit\nFROM (\n\tSELECT COUNT(id) count\n\tFROM growth_sessions gs\n\tWHERE attendee_limit > 1000 AND gs.date BETWEEN '$from' AND '$to'\n\tGROUP BY attendee_limit\n) data;"
    }
   ]
  }
 ]
}